version: "3"
services: 
    blockchain:
        build:
            context: .
            dockerfile: hmcoin/dockerfile
    frontend:
        build:
            context: .
            dockerfile: hmcoin-frontend/dockerfile