FROM python:3.8.0-alpine

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY hmcoin/ .
RUN ls
EXPOSE 8080
RUN ["python ./manage.py migrate"]
CMD [ "python", "manage.py", "runserver" ]
