# Generated by Django 3.1.6 on 2021-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210204_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='proof',
        ),
        migrations.AddField(
            model_name='transaction',
            name='proof',
            field=models.IntegerField(null=True),
        ),
    ]
