
# Dockerfile for the Service

FROM golang:1.14 as build
WORKDIR /app
ADD hmcoin-frontend ./frontend
ADD hmcoin-frontend/go.mod .
ADD hmcoin-frontend/go.sum .
WORKDIR ./frontend
RUN ls
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build ./frontend

FROM alpine:latest
COPY --from=build /app/frontend /app/
COPY /frontend/js-frontend/build /app/js-frontend/build
WORKDIR /app
EXPOSE 8080
ENTRYPOINT [ "./frontend" ]