
# Dockerfile for the Service

FROM golang:1.14 as build
WORKDIR /app
ADD hmcoin-frontend ./frontend
ADD hmcoin-frontend/go.mod .
ADD hmcoin-frontend/go.sum .
RUN go build -o frontend frontend/main.go

FROM alpine:latest
COPY --from=build /app/frontend /app/
COPY /hmcoin-frontend/js-frontend/build /app/js-frontend/build
WORKDIR /app
EXPOSE 8081
ENTRYPOINT [ "./frontend" ]